import { randomUUID } from "node:crypto";
import { completeJson } from "../llm/llmClient.js";
import { PLANNER_PROMPT } from "../llm/prompts.js";
import { Plan } from "../types.js";

interface PlannerResponse {
  reasoning: string;
  steps: string[];
}

export class PlannerAgent {
  async createPlan(goal: string): Promise<{ plan: Plan; usage: { promptTokens: number; completionTokens: number; totalTokens: number } }> {
    try {
      const response = await completeJson<PlannerResponse>(`Goal: ${goal}`, PLANNER_PROMPT, 500);
      const steps = (response.content.steps ?? []).slice(0, 8);

      return {
        plan: {
          goal,
          reasoning: response.content.reasoning || "Plan generated by Planner Agent",
          steps: steps.map((description) => ({
            id: randomUUID(),
            description,
            status: "pending",
            retries: 0
          }))
        },
        usage: response.usage
      };
    } catch {
      const fallbackSteps = [
        "Clarify objective and constraints",
        "Execute the most direct implementation step",
        "Validate the outcome against the objective",
        "Summarize results and unresolved items"
      ];

      return {
        plan: {
          goal,
          reasoning: "Fallback plan generated due to planner parse failure",
          steps: fallbackSteps.map((description) => ({
            id: randomUUID(),
            description,
            status: "pending",
            retries: 0
          }))
        },
        usage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 }
      };
    }
  }
}
